EvitanRelta/markgh

package-lock.json, package.json, src/App.tsx
Console displays a warning when calling `setContent` for the persisted text (Issue #58 )
=> Add feature to allow for editor text to persist

package-lock.json, package.json, src/App.tsx, src/components/Body/Body.tsx, src/components/Editor/TextEditor.tsx, src/components/Footer/ImageContainer.jsx, src/components/Header/ToolbarOptions/FileMenu/ImportGHRepo.tsx, src/converterFunctions/toMarkdown.ts
- Resolves Issue #58 & other compiler warnings
=> Fix persistent text warnings 

src/App.tsx, src/components/Body/Body.tsx, src/components/Body/MarkdownTextContainer.tsx, src/components/Editor/AlignDropDown.tsx, src/components/Editor/EditorToolbar.tsx, src/components/Editor/HeadingDropDown.tsx, src/components/Editor/TextEditor.tsx, src/components/Footer/Footer.tsx, src/components/Footer/ImageContainer.jsx, src/components/Footer/Version.tsx, src/components/Header/Header.tsx, src/components/Header/MenuButton.tsx, src/components/Header/MenuOptions/ExportMarkdownOption.tsx, src/components/Header/MenuOptions/ThemeOption.tsx, src/components/Header/MenuOptions/UploadFileOption.tsx, src/components/Header/ToolbarContainer.jsx, src/components/Header/ToolbarOptions/FileMenu/ExportFile.jsx, src/components/Header/ToolbarOptions/FileMenu/FileOption.tsx, src/components/Header/ToolbarOptions/FileMenu/OpenFile.jsx
=> Refactor elements to use MUI

package-lock.json, package.json, src/App.tsx
Features:
- Verification key for google (currently a placeholder example)
- Keywords for google search
- Brief description for website when it appears as search result
Note:
No changes in code or functionality besides the added wrappers `HelmetProvider` and `Helmet`, wrapped around the entirety of the returned components in 'App.tsx', along with the `<meta/>` tags for the features listed above.
=> Add support for SEO in Google search

src/components/Header/ToolbarOptions/FileMenu/ImportGHRepo.tsx
big momma => bad 👎
slim & sexy 👍
=> Resize 'OK' button 

src/components/Header/ToolbarOptions/FileMenu/ImportGHRepo.tsx
- Support for 'Enter' key to import
- Add helper text for reminding user to login if it's a private repo
- Reword error messages
- Reposition loading circle
=> Minor changes for 'Import Repo' feature

src/components/Header/Header.tsx
=> Fix for uninitialised 'Snapshot' field if using old IndexedDB 

src/components/Body/Body.tsx, src/components/Body/MarkdownTextContainer.tsx, src/components/Editor/AlignDropDown.tsx, src/components/Editor/EditorToolbar.tsx, src/components/Editor/HeadingDropDown.tsx, src/components/Footer/Footer.tsx, src/components/Footer/Version.tsx, src/components/Header/Header.tsx, src/components/Header/TitleInput.tsx, src/components/Header/ToolbarOptions/FileMenu/ExportFile.tsx, src/components/Header/ToolbarOptions/FileMenu/FileOption.tsx, src/components/Header/ToolbarOptions/FileMenu/ImportGHRepo.tsx, src/components/Header/ToolbarOptions/FileMenu/OpenFile.tsx, src/components/Header/ToolbarOptions/Snapshots/LastEdited.tsx, src/components/Header/ToolbarOptions/Snapshots/SnapshotIcon.tsx, src/components/Header/ToolbarOptions/Snapshots/SnapshotOption.tsx, src/components/Header/ToolbarOptions/Snapshots/VersionIndex.tsx
=> Abstract inline styles

src/components/Header/ToolbarOptions/FileMenu/ImportGHRepo.tsx, src/components/Header/ToolbarOptions/FileMenu/RepoLinkInput.tsx
=> Abstract out GitHub repo link input

src/components/Header/Header.tsx, src/components/Header/ToolbarOptions/Snapshots/VersionIndex.tsx
=> Fix behaviour of loading in untitled snapshots

public/index.html
=> Search result description optimisation

src/components/Header/ToolbarOptions/Snapshots/VersionIndex.tsx, src/store/snapshotThunks.ts
=> Add button to clear all snapshots

src/components/Header/ToolbarOptions/Snapshots/VersionIndex.tsx
=> Overflow text of snapshot titles in 'VersionIndex' will ellipse

src/components/Header/ToolbarOptions/ExportMenu/PushRepoLinkInput.tsx, src/scripts/helpers/updateGitHubReadme.ts
=> Fix Error 409 handling

src/scripts/helpers/updateGitHubReadme.ts
=> Update PR body if PR is already created before from Push feature

src/components/Header/ToolbarOptions/ExportMenu/PushRepoLinkInput.tsx, src/scripts/helpers/updateGitHubReadme.ts
=> Push uses markdown instead of innerHTML

src/components/Editor/EditorFormatOption.tsx, src/components/Editor/EditorToolbar.tsx
=> Abstract out format option mapping

src/components/Body/Body.tsx, src/components/Editor/EditorFormatOption.tsx, src/components/Editor/EditorToolbar.tsx
=> Abstract option map

src/components/Editor/EditorFormatOption.tsx, src/components/Editor/EditorToolbar.tsx, src/components/Header/ToolbarOptions/ExportMenu/PushGHDialog.tsx
=> UI bug fixes

src/components/Header/ToolbarOptions/ImportMenu/RepoLinkInput.tsx
Removes the use of CORS proxy in importing GitHub markdowns with Octokit, which doesn't require a CORS proxy.
Fixes #202
=> Replace the use of CORS proxy with 'Octokit' package
